### PR TITLE
Renames try_load_module to load_object because api change

### LINKED ISSUE #73: Printer instance has no attribute 'try_load_module'
I have been trying to install dwc2 for 2 days.  I was running octoprint with klipper and tried installing as described at:

https://github.com/Stephan3/dwc2-for-klipper

but that fails at wget https://github.com/chrishamm/DuetWebControl/releases/download/2.1.6/DuetWebControl-SBC.zip
 with the error indicating 2.1.6 does not exist.  I tried using:
wget https://github.com/chrishamm/DuetWebControl/releases/download/2.0.0-RC5/DuetWebControl.zip

which is described at:https://klipper.info/klipper-+-dwc2-1/installing-dwc2

That installed but the gui would not come up.  If I open octoprint the klipper  console "status" says:

Internal error during connect: Printer instance has no attribute 'try_load_module'

I even tried installing on a clean raspbian system with the installer.sh  descibed at:https://github.com/manu7irl/klipper-DWC2-installer?files=1.
I only have one printer so this is more that I need but I tried it anyway.  
With this I could not get dwc2, or octoprint guis to open and of course klipper then is not running.

I did install this a few months ago and it worked but I decided not to switch then so went back to octoprint. (no longer installed).

**The dwc2 gui fails to open(Unable to connect), and klipper does not start with this try_load_module error.**  

What next????

### PR DESCRIPTION
**Pull request by netonjm**
Fixes API break in printer.try_load_module

https://github.com/KevinOConnor/klipper/commit/787ed452c2abe3bad81ffaf732b0b2609e3534bb

now webserver intializes again.

IMAGE 2020-05-16 14:34:47

Fixes https://github.com/Stephan3/dwc2-for-klipper/issues/73

### CODE REVIEW

**Comment by Kszajga** [comment]
I did the same in local, it is working perfectly for me.

**Comment by netonjm** [comment]
@Stephan3 thoughs?

**Comment by Tomblarom** [comment]
Thanks! I can confirm that this PR fixes the 'try_load_module' Error with the latest DWC2 version!

**Comment by NedalLive** [comment]
Thanks for the fix! it would be cool to apply it to make it easier!

**Comment by Stephan3** [comment]
i picked that one up to a single commit. Thanks for orking that out @netonjm

**Comment by netonjm** [comment]
It was on a single commit without conflicts, sad because it was not merged 😿

**Comment by Stephan3** [comment]
@netonjm dont get me wrong. You had the right idea.

I decided to use lookup_object instead. If needed it fails gently.
https://github.com/Stephan3/dwc2-for-klipper/blob/5953e779e5cc2f226e3daabf835a6477ecd49974/web_dwc2.py#L48

**Pull request closed without merging**
