### PR TITLE
Copy Slic3r PE regular expressions for PrusaSlicer gcode support

### PR DESCRIPTION
**Pull request by pierre-vo**
Simple copy of the lines. I just fed a PrusaSlicer file to it and the "Based on layer" and "based on slicer" times are working.

### CODE REVIEW

**Comment by pierre-vo** [comment]
Filament used regular expression does not work, I won't be able to test other regexp before a week.

**Comment by Stephan3** [comment]
Make the details work and it will merge. Thanks for that

**Comment by pierre-vo** [comment]
@Stephan3 I finally got time to test with the 2nd commit and the filament usage is displayed in the job list, all 4 estimates are displaying values and the favicon is being updated while printing.
I think it is ready to be merged.

**Comment by jakep82** [comment]
Working for me.

**Pull request merged**
